version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - run: 
          name: Fetch git tags 
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects 
          command: git gc
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  bundle_install:
    description: "Bundle install"
    steps:
      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile" }}
            - bundle-v1-
      - run:
          name: Bundle install
          command: |
            bundle install --path ./modules
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile" }}
          paths:
            - "modules"
  release:
    description: "Build Jekyll site"
    steps:
      - restore_cache:
          keys:
            - _site-v1-{{ CIRCLE_SHA1 }}
            - _site-v1-
      - run:
          name: Building Jekyll site
          command: bundle exec jekyll build --incremental
      - save_cache:
          name: Save build cache
          key: _site-v1-{{ CIRCLE_SHA1 }}
          paths:
            - _site
  docker_build:
    description: "Build Docker image"
    steps:
      - setup_remote_docker
      - run: 
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_TAG:-latest} .
  docker_push:
    description: "Push image to docker hub"
    steps:
      - run: 
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_TAG:-latest}
  k8s_deploy:
    description: "Deploy to k8s cluster"
    steps:
      - k8s/install-kubectl
      - run: 
          name: Deploying to k8s cluster for service binary-academy
          command: |
            echo $CA_CRT | base64 --decode > ca.crt
            kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/binary-academy << parameters.k8s_svc_name >>=${DOCKHUB_ORGANISATION}/binary-static-academy:${CIRCLE_TAG}

jobs:
  release:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - git_checkout_from_cache
      - bundle_install
      - release
      - docker_build
      - docker_push
      
  deploy_production:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - k8s_deploy
      
workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only: /^master/

